### ISSUE TITLE
Unable to build v0.104.0-xx 

### ISSUE THREAD

**Issue by gxgani** [AdguardTeam/AdGuardHome#2117]
Tried building snapshots for edge and beta channel but I'm unable to it with v0.104-x tag, always falls to v0.103.3.

**Comment by ameshkov** [comment]
> always falls to v0.103.3

I don't fully understand what do you mean.

How exactly do you build it?

**Comment by gxgani** [comment]
```
git clone https://github.com/AdguardTeam/AdGuardHome
cd AdGuardHome
make release CHANNEL=edge/beta
```
Log:
```
Starting release build: version v0.103.3-SNAPSHOT-3a71374f, channel beta
CHANNEL=beta goreleaser release --rm-dist --skip-publish

   • releasing...     
   • loading config file       file=.goreleaser.yml
   • running before hooks
      • running go mod download
      • running go generate ./...
   • loading environment variables
   • getting and validating git state
      • releasing v0.104.0-beta1, commit 3a71374f9ff4484248ecb073f0a7282cec56ba23
```

**Comment by ameshkov** [comment]
Fixed it, thank you!

**Comment by gxgani** [comment]
> Fixed it, thank you!

I am not still not able to build edge/beta releases. It's always building 103.3.

Am I missing anything before the make process?
