### ISSUE TITLE
optical issue on statistic page/box

### ISSUE THREAD

**Issue by uservictor** [AdguardTeam/AdGuardHome#2942]
Hi I use AGH v0.106.0-a.110+8b8319fc (also on previous versions) on my raspberrypi and get often this bug.
(it appears on mobile and desktop browser)
Sometimes the graph line green or yellow is affected too (malware/adult stats) its then in the middle of the box.

![agh optical issue-cleaned](https://user-images.githubusercontent.com/56163305/114332263-296da680-9b46-11eb-9a35-6188f2d2bc0d.jpg)

It happens very often if i set to german language but from time to time it appears also on englisch language.

Have a nice day

**Comment by ainar-g** [comment]
@uservictor, @zadigre, it seems like this is fixed on latest edge builds.  Could any of you please check if it is also fixed for you?

**Comment by zadigre** [comment]
> @uservictor, @zadigre, it seems like this is fixed on latest edge builds. Could any of you please check if it is also fixed for you?

it looks fine with the latest edge build... 
but that said, it wasn't happening all the time... and it was fine like 12 hours ago, shortly after posting this bug report. 
I'll report back if I ever see this problem again.

**Comment by uservictor** [comment]
After update to v0.106.0-a.122+d7b2d63e i can still see it, its not an permanent issue, most of the time its fine.
![agh-cleaned](https://user-images.githubusercontent.com/56163305/114593114-03eab500-9c8c-11eb-8379-2210b20f66bd.jpg)

**Comment by ainar-g** [comment]
Hm.  Really weird.  We'll dig further, thanks for the feedback.

**Comment by uservictor** [comment]
you're welcome, let me know if you need more information.

**Comment by ameshkov** [comment]
Probably, we should simply postpone this one since we cannot reproduce this.

We will anyway redesign the dashboard completely soon, it makes little sense to do the double-work.
