### ISSUE TITLE
All DHCP Static Leases are gone after update 106

### ISSUE THREAD

**Issue by Vercety87** [AdguardTeam/AdGuardHome#3027]
### Issue Details

After upgrading my ADGH docker container, I loose all my DHCP Static Leases

* **Version of AdGuard Home server: v 0.106.0
* **How did you install AdGuard Home:  Docker-compose
* **How did you setup DNS configuration: DHCP via AdGuard Home
* **CPU architecture: x86_64
* **Operating system and version: Ubuntu 20.04

### Expected Behavior
Find all my previous DHCP Static Leases from previous version of ADGH

### Actual Behavior
No DHCP Static Leases found

### Additional Information
DHCP Static Leases seams to still be in ADGH Database, logs says :

```
adguardhome    | 2021/04/28 20:50:59 [info] dhcp: stored 32 leases in DB
```

**Comment by Tloram** [comment]
Same issue here, not all, but some of my static leases seem to have been removed since the update last night to v0.106.0

Please look into this asap as this will be causing some serious problems with my local network now!

**Comment by DavidPasch** [comment]
Same issue here ... all static DHCP leases are gone.

**Comment by ainar-g** [comment]
@Vercety87, @DavidPasch, thank you for your reports.  We're investigating that.  Can you please look into the `leases.db` file in AGH's workdir and tell us if there is duplicated or invalid data in the `"host"` fields there?

This is probably caused by #2952, and we'll probably need to release a migration for that in v0.106.1.

**Comment by DavidPasch** [comment]
No duplicates but (maybe) invalid HostNames using "blank space" character in their names.

**Comment by ainar-g** [comment]
The fix was pushed to the edge channel in snapshot c8092fe recently.  It should apply a best-effort algorithm to make previously added invalid hostnames of the static DHCP leases valid, so most of them should reappear.  Can you please check if that fix works for you?

**Comment by DavidPasch** [comment]
Had installed AdGuard manually, not via snap. So no access to that edge cannel source. Sorry.

**Comment by Vercety87** [comment]
> The fix was pushed to the edge channel in snapshot [c8092fe](https://github.com/AdguardTeam/AdGuardHome/commit/c8092fe34d62f00ee6c224c0eddbdb5a58ec3bcc) recently. It should apply a best-effort algorithm to make previously added invalid hostnames of the static DHCP leases valid, so most of them should reappear. Can you please check if that fix works for you?

Hi, thanks for your help. I just tried the latest edge v0.107.0-a.5+59f48d79 but still the same problem.

I got this in logs file :

`adguardhome_edge    | 2021/04/29 18:08:04 [info] dhcpv4: normalized hostname "" into "192-168-0-5"
adguardhome_edge    | 2021/04/29 18:08:04 [info] dhcp: stored 32 leases in DB
adguardhome_edge    | 2021/04/29 18:08:04 [info] dhcpv4: normalized hostname "" into "192-168-0-5"
adguardhome_edge    | 2021/04/29 18:08:04 [info] dhcp: stored 32 leases in DB
adguardhome_edge    | 2021/04/29 18:09:25 [info] dhcpv4: IP conflict: 192.168.0.11 is already used by another device
adguardhome_edge    | 2021/04/29 18:09:25 [info] dhcpv4: IP conflict: 192.168.0.12 is already used by another device
adguardhome_edge    | 2021/04/29 18:09:26 [info] dhcp: stored 35 leases in DB
adguardhome_edge    | 2021/04/29 18:09:26 [info] dhcp: stored 35 leases in DB`

I will check device name in leases.db file.

**Comment by ainar-g** [comment]
Thanks for testing and providing the output.  The hostname migration we've implemented works well, but apparently there are also several records with the same IP address in your leases.  We will have to think if we can fix that automatically.

**Comment by Vercety87** [comment]
My bad I was on a bad leases.db. I just push one of my backup, into edge version and all my DHCP leases are back.
Thanks for the fix.

**Comment by ainar-g** [comment]
Thanks for the good news!  We will release the fix with v0.106.1 in the next couple of days.  I'll close this issue for now.
