### ISSUE TITLE
DHCP Issue again. 

### ISSUE THREAD

**Issue by Black8all** [AdguardTeam/AdGuardHome#3053]
Hi, after few test, I have some trouble again with the DHCP. Some of my devices can't obtain an IP and I need to set a static lease if I want it to work. 

I also encounter some of disconnection with few other. In the end, my log file are flooded by message about normalisation error. 

I run now the 1.0.6.1 b1

Best regards 

[AdGuard.log](https://github.com/AdguardTeam/AdGuardHome/files/6409005/AdGuard.log)

_Originally posted by @Black8all in https://github.com/AdguardTeam/AdGuardHome/issues/2978#issuecomment-830565777_

**Comment by zhangguanzhang** [comment]
same issue

**Comment by ainar-g** [comment]
Hi, and thank you for the thorough report.  From the logs, it seems like your installation's `leases.db` has a lot of duplicated IP addresses.  Do you have a lot of static leases?  Could you add the IP range that is used in the DHCP server as well as the IPs of the static leases?  Thanks!

**Comment by Black8all** [comment]
No I haven't a lot of static leases. Instead of the two last in the list (those who don't work with dynamic DHCP) I usually only have 4 static.

![Screenshot_20210504-180829_Firefox.jpg](https://user-images.githubusercontent.com/67442874/117035228-599f0400-ad04-11eb-8ff8-8ec72cfb02bd.jpg)
![Screenshot_20210504-180934_Firefox.jpg](https://user-images.githubusercontent.com/67442874/117035235-5d328b00-ad04-11eb-8e3b-f9f8526db927.jpg)

**Comment by ainar-g** [comment]
I see, thanks.  This may be the same issue as #3056.  We're planning a patch in the next few days for it.

**Comment by ainar-g** [comment]
We've pushed a possible fix to the edge channel.  Could you please check if our solution makes the DHCP server work better?

**Comment by Black8all** [comment]
I'll test this as soon as I get home 😉



Le jeu. 6 mai 2021 à 17:03, Ainar Garipov ***@***.***> a
écrit :

**Comment by Black8all** [comment]
I updated to version 0.106.2 b1 and it seems to work. I deleted all the static leases that I had to set up manually and at the moment all of my devices got an IP quickly. I'll juste wait until all my dynamics   leases renew.

**Comment by Black8all** [comment]
Finally I withdraw what I just said.  Some of my devices still don't have internet access, despite having an IP assigned by DHCP.  I'll post the log soon.

**Comment by Black8all** [comment]
The log is pretty similar as before :

>2021/05/06 21:10:23 [info] dhcpv4: normalized hostname "TOSHIBA-TV" into "toshiba-tv"
2021/05/06 21:10:23 [info] dhcp: stored 31 leases in DB
2021/05/06 21:10:26 [info] dhcpv4: normalized hostname "TOSHIBA-TV" into "toshiba-tv"
2021/05/06 21:10:26 [info] dhcp: stored 31 leases in DB
2021/05/06 21:10:29 [info] dhcpv4: normalized hostname "TOSHIBA-TV" into "toshiba-tv"
2021/05/06 21:10:30 [info] dhcp: stored 31 leases in DB
2021/05/06 21:10:33 [info] dhcpv4: normalized hostname "TOSHIBA-TV" into "toshiba-tv"
2021/05/06 21:10:33 [info] dhcp: stored 31 leases in DB
2021/05/06 21:10:36 [info] dhcpv4: normalized hostname "TOSHIBA-TV" into "toshiba-tv"
2021/05/06 21:10:36 [info] dhcp: stored 31 leases in DB
2021/05/06 21:10:39 [info] dhcpv4: normalized hostname "TOSHIBA-TV" into "toshiba-tv"
2021/05/06 21:10:39 [info] dhcp: stored 31 leases in DB
2021/05/06 21:10:43 [info] dhcpv4: normalized hostname "TOSHIBA-TV" into "toshiba-tv"
2021/05/06 21:10:43 [info] dhcp: stored 31 leases in DB
2021/05/06 21:10:46 [info] dhcpv4: normalized hostname "TOSHIBA-TV" into "toshiba-tv"
2021/05/06 21:10:46 [info] dhcp: stored 31 leases in DB
2021/05/06 21:10:49 [info] dhcpv4: normalized hostname "TOSHIBA-TV" into "toshiba-tv"
2021/05/06 21:10:49 [info] dhcp: stored 31 leases in DB
2021/05/06 21:10:52 [info] dhcpv4: normalized hostname "TOSHIBA-TV" into "toshiba-tv"
2021/05/06 21:10:53 [info] dhcp: stored 31 leases in DB
2021/05/06 21:10:56 [info] dhcpv4: normalized hostname "TOSHIBA-TV" into "toshiba-tv"
2021/05/06 21:10:56 [info] dhcp: stored 31 leases in DB

It's this device that can't get internet access --^


> 2021/05/07 07:09:52 [info] dhcpv4: normalized hostname "ESP_839FAC" into "esp-839fac"
2021/05/07 07:09:52 [info] dhcp: stored 31 leases in DB
2021/05/07 07:09:52 [info] dhcpv4: normalized hostname "ESP_839FAC" into "esp-839fac"
2021/05/07 07:09:52 [info] dhcp: stored 31 leases in DB
2021/05/07 07:09:52 [info] dhcpv4: normalized hostname "ESP_839FAC" into "esp-839fac"
2021/05/07 07:09:53 [info] dhcp: stored 31 leases in DB
2021/05/07 07:09:53 [info] dhcpv4: normalized hostname "ESP_839FAC" into "esp-839fac"
2021/05/07 07:09:53 [info] dhcp: stored 31 leases in DB
2021/05/07 07:09:55 [info] dhcpv4: normalized hostname "ESP_839FAC" into "esp-839fac"
2021/05/07 07:09:55 [info] dhcp: stored 31 leases in DB
2021/05/07 07:09:56 [info] dhcpv4: normalized hostname "ESP_839FAC" into "esp-839fac"
2021/05/07 07:09:56 [info] dhcp: stored 31 leases in DB
2021/05/07 07:09:56 [info] dhcpv4: normalized hostname "ESP_839FAC" into "esp-839fac"
2021/05/07 07:09:56 [info] dhcp: stored 31 leases in DB
2021/05/07 07:09:57 [info] dhcpv4: normalized hostname "ESP_839FAC" into "esp-839fac"
2021/05/07 07:09:57 [info] dhcp: stored 31 leases in DB
2021/05/07 07:09:57 [info] dhcpv4: normalized hostname "ESP_839FAC" into "esp-839fac"
2021/05/07 07:09:58 [info] dhcp: stored 31 leases in DB
2021/05/07 07:09:58 [info] dhcpv4: normalized hostname "ESP_839FAC" into "esp-839fac"
2021/05/07 07:09:58 [info] dhcp: stored 31 leases in DB
2021/05/07 07:09:59 [info] dhcpv4: normalized hostname "ESP_839FAC" into "esp-839fac"
2021/05/07 07:09:59 [info] dhcp: stored 31 leases in DB
2021/05/07 07:09:59 [info] dhcpv4: normalized hostname "ESP_839FAC" into "esp-839fac"
2021/05/07 07:09:59 [info] dhcp: stored 31 leases in DB
2021/05/07 07:10:00 [info] dhcpv4: normalized hostname "ESP_839FAC" into "esp-839fac"
2021/05/07 07:10:00 [info] dhcp: stored 31 leases in DB
2021/05/07 07:10:00 [info] dhcpv4: normalized hostname "ESP_839FAC" into "esp-839fac"
2021/05/07 07:10:00 [info] dhcp: stored 31 leases in DB
2021/05/07 07:10:00 [info] dhcpv4: normalized hostname "ESP_839FAC" into "esp-839fac"
2021/05/07 07:10:00 [info] dhcp: stored 31 leases in DB
2021/05/07 07:10:00 [info] dhcpv4: normalized hostname "ESP_839FAC" into "esp-839fac"
2021/05/07 07:10:00 [info] dhcp: stored 31 leases in DB
2021/05/07 07:10:00 [info] dhcpv4: normalized hostname "ESP_839FAC" into "esp-839fac"
2021/05/07 07:10:00 [info] dhcp: stored 31 leases in DB
2021/05/07 07:10:01 [info] dhcpv4: normalized hostname "ESP_839FAC" into "esp-839fac"
2021/05/07 07:10:01 [info] dhcp: stored 31 leases in DB
2021/05/07 07:10:01 [info] dhcpv4: normalized hostname "ESP_839FAC" into "esp-839fac"

And it's the same for all my leases, I have this two message in loop.

**Comment by ameshkov** [comment]
Weird, we need verbose-level log to see what's happening.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.

**Comment by Black8all** [comment]
Ok, I'll do that. Strangely, I had already activated the verbose mode, but apparently it was not saved after the update.

**Comment by ameshkov** [comment]
@Black8all you need to stop AGH before changing verbose flag.

**Comment by Black8all** [comment]
I reproduce the issue with verbose mode on, I have posted below the log file only from the moment I removed the static lease to let DHCP assign an IP to my device. Despite getting an IP, the device has no access to the internet (it's a toshiba smart TV) and I guess that for a period of 45min the logs are huge.

[AdGuard.log](https://github.com/AdguardTeam/AdGuardHome/files/6444617/AdGuard.log)

**Comment by Black8all** [comment]
![Screenshot_20210508-023837_Settings.jpg](https://user-images.githubusercontent.com/67442874/117561664-0547ab80-b099-11eb-910d-267d38d1769e.jpg)

If it can help, this is the message on my Galaxy S20 when it obtain an IP from the DHCP without static lease set.

**Comment by Black8all** [comment]
Today it's worst than ever, few of my devices can't obtain an IP, or if it obtain it, they don't have internet access. I need to set lot of statics lease for temporary solve the issue.

**Comment by ainar-g** [comment]
We've pushed some DHCP changes to the `edge` revision c890f5c1.  Could you please check if it makes the problem better?

Also, if you don't have a lot of static leases, and you don't mind adding them manually, you could also remove the `leases.db` file in AGH's workdir to make sure that old corrupted data isn't interfering with the new server logic.

Thanks.

**Comment by Black8all** [comment]
Okay, I'll test this right away. Normally when DHCP is working normally I only have 4 static leases, so it's not a big deal if I have to set them up again by hand. I have a lot more right now because of the problem with DHCP.

Thanks for your work.

**Comment by Black8all** [comment]
It's ok, I done the update and removed my leases.db. 

Here is the log file from when I did the update and apparently I still have the same problem. For the moment only a few of my devices have tried to get an IP but the same messages keep coming up. On the other hand, those one get an IP (with difficulty) and internet connection but some others still don't. 

[AdGuard - Copie.log](https://github.com/AdguardTeam/AdGuardHome/files/6472767/AdGuard.-.Copie.log)

**Comment by ainar-g** [comment]
Thank you for the log.  We will research it further.

**Comment by Black8all** [comment]
In the log file, you'll see one device who tries to to gain the 192.168.1.18 IP. This device is one of my chromecast-audio and at this time it doesn't obtain it.
![Screenshot_20210513-170719.jpg](https://user-images.githubusercontent.com/67442874/118145236-b0e05b00-b40d-11eb-8680-0f801b4b7a24.jpg)

**Comment by ainar-g** [comment]
@Black8all, what is the value of `dhcp.dhcpv4.icmp_timeout_msec` in your config?  If you increase it to, say, `3000`, does anything change?

**Comment by Black8all** [comment]
It was previously set to 1000, I increased it to 3000. 
[AdGuard - Copie.log](https://github.com/AdguardTeam/AdGuardHome/files/6473830/AdGuard.-.Copie.log)
This is the log since the change.

![image](https://user-images.githubusercontent.com/67442874/118156632-e12df680-b419-11eb-9014-59e2ba497d63.png)
This time it seem to obtain his IP.

![image](https://user-images.githubusercontent.com/67442874/118156766-07539680-b41a-11eb-9d8e-604f92bd255d.png)
But still no host-name

**Comment by ainar-g** [comment]
Thank you very much!  I think that we have a couple of ways of improving the situation now.  You should probably keep the new timeout value at least for now.

**Comment by Black8all** [comment]
Unfortunately always the same thing, all this log is only for one device.
[AdGuard - Copie (2).log](https://github.com/AdguardTeam/AdGuardHome/files/6474054/AdGuard.-.Copie.2.log)

**Comment by ainar-g** [comment]
Is this a manually filtered log?  If so, have you noticed any requests from that machine with the `DECLINE` message type?  An unfiltered log would be more helpful.

Also, just to be safe, there are no other DHCP servers in that network, correct?

**Comment by Black8all** [comment]
This is not a filtered log, I just selected the logs from when one of my hosts tried to get an IP, to the end of the file. The whole log file is over 90MB and not all of it is relevant.
I don't know if there were any DECLINE messages, I didn't have time to read everything yesterday.

Because of my ISP, I had to configure two DHCP, because my TV set-top box only wants an IP from the ISP box. The DHCP range of the ISP box is 192.168.1.2 to 192.168.1.3. and I have set up two static leases on the ISP box. One for the decoder .2 and one for my NAS .3 (which hosts AGH). 

Then the DHCP of AGH takes over on a range from 192.168.1.5 to 192.168.1.150.

I know it's not very clean but it's the only way I can use AGH and my IPTV. And as far as I remember it worked well with version 0.105.2.

**Comment by ainar-g** [comment]
I see.  Unfortunately, configurations with two DHCP servers in one network aren't really supported by AGH, sorry.  We'll try to make a few more fixes in v0.106.3, but we cannot guarantee that they will fix the issue, as again, such configurations aren't currently supported.

**Comment by Black8all** [comment]
OK, it's a shame, I really appreciate AGH 😢, I'll try to rollback to 0.105.2 for see if it worked. If so I would stay on this version 😅.

**Comment by ainar-g** [comment]
The latest `edge` build contains some enhancements that should make the DHCP server behave better.

**Comment by Black8all** [comment]
Nice 👍I'll test this this evening.

**Comment by Black8all** [comment]
I just updated to the v0.107.0-a.29+5acae6e2, I'll see if it's better.

**Comment by Black8all** [comment]
Apparently nothing has changed for me with this update.
[AdGuard - Copie (2).log](https://github.com/AdguardTeam/AdGuardHome/files/6496975/AdGuard.-.Copie.2.log)

**Comment by ainar-g** [comment]
@Black8all, we've improved logging a bit in the most recent `edge` build (b2e3e4d0).  Could you please provide a **full** log after:

1.  Updating.
2.  Restarting AGH.
3.  Keeping it working for about five minutes.

The restart and the full log are very important.  If you would like to make it more private, you could sent it to devteam@adguard.com with the subject line “AdGuard Home Issue 3053”.

We still don't see why the DHCP clients would behave the way they behave and which changes in v0.106 branch caused it, but we're looking into it further.

**Comment by Black8all** [comment]
Thanks you very much for your hard work. I'll do that as soon as I get back to home.

**Comment by ainar-g** [comment]
We have received the logs, thanks.  We will inspect them and see if we can improve something more in the nearest days.

**Comment by ainar-g** [comment]
@Black8all, I remember I proposed that you increase `dhcp.dhcpv4.icmp_timeout_msec`.  Can you please reset it to `1000` or perhaps set it even lower, to `500`?  Perhaps the client has a very low DHCP timeout, and now that `DECLINE` messages are processed, the risk of IP conflicts should become lower.

**Comment by MarsWarrior** [comment]
> I see. Unfortunately, configurations with two DHCP servers in one network aren't really supported by AGH, sorry. We'll try to make a few more fixes in v0.106.3, but we cannot guarantee that they will fix the issue, as again, such configurations aren't currently supported.

But this is a completely valid configuration: two DHCP servers with different ranges (split scope) as you can read in this stackexchange question/answer [Can I have multiple DHCP servers on one network? ](https://serverfault.com/questions/368512/can-i-have-multiple-dhcp-servers-on-one-network)

I have the same. My ISP's modem can't disable the DHCP server, so this server is only handling some non existent mac address, meaning it doesn't do anything on my network!

On the other hand I'm using redundant AGH docker containers using bakito's [adguardhome-sync](https://github.com/bakito/adguardhome-sync) to fully (config, dns, dhcp) sync the instances.

So I have 3 DHCP servers running on my network using static leases.

**Comment by zhangguanzhang** [comment]
could add option for it in the configuration.

**Comment by anbraten** [comment]
@Black8all I can't get IPs for my ESPs and some other IoT stuff as well. It seem to me that this issue is coming from the fact that ESPs etc. expect a Unicast response from the DHCP server, but currently the ADH DHCP is only responding with Broadcasts. After I changed some code in #3458, it worked was able to receive IPs with my ESPs etc.

**Comment by ainar-g** [comment]
@Black8all, hello. We've made another round of improvements to the DHCP server.  We'll close this issue for now, but if you find any new issues with the latest `edge` builds, please report them.

**Comment by Black8all** [comment]
Hi,

thanks for your hard works, I don't have the time right now to test that,
but I'll try ASAP 👍

Le jeu. 30 sept. 2021 à 19:05, Ainar Garipov ***@***.***> a
écrit :
