### ISSUE TITLE
Cannot enable DHCP server: Cannot check if IP is static

### ISSUE THREAD

**Issue by mkap20** [AdguardTeam/AdGuardHome#3289]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.3, FreeBSD amd64
* **How did you install AdGuard Home:**
  * FreeBSD pkg
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * TP-Link Archer a9
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * FreeBSD 12.2-RELEASE-p6

### Expected Behavior
DHCP server option should successfully detect if existing DHCP server exists on network. Attempting to enable the DHCP server should be successful if none exists.

### Actual Behavior
"Enable DHCP server" is grayed out. If I try to manually enable it via editing the .yaml, I get an error on the GUI: `Error: control/dhcp/set_config | enabling dhcp: checking static ip: cannot check if IP is static: not supported on freebsd | 500` If I use the "Check for DHCP servers" button, I get `Error: control/dhcp/find_active_dhcp | Network Error`

### Additional Information
In my case, I do have a static IP set up. Is setting up AdGuard as a DHCP server not supported in FreeBSD? If it is, then what am I doing wrong?

**Comment by ainar-g** [comment]
Hi, and thank you for the report.  There are definitely some features missing, but enabling through the config should work.  We'll look into it.

**Comment by TheRandMan** [comment]
Having the same problem on ARM64 FreeBSD. I manually enabled it in the config and it seems to somewhat work but there are still issues. I've attached DHCP related logs. 

[adguard-dhcp.log](https://github.com/AdguardTeam/AdGuardHome/files/6797504/adguard-dhcp.log)

**Comment by EugeneOne1** [comment]
@mkap20, we've just updated the edge channel with the build that should fix the issue for you.  Could you please check it?

@TheRandMan, it seems, that in your case AdGuard Home can't bind on the port `68`.  Is it launched with root permissions?

**Comment by mkap20** [comment]
Just installed and checked today. Issue still looks the same, except this time I also get `receiving packet: invalid argument` if I try to check for DHCP servers through the GUI.

**Comment by EugeneOne1** [comment]
@mkap20, just to clarify:
1.  What exact version of AdGuard Home did you installed (it's printed in the right bottom corner of the AdGuard Home's dashboard)?
1.  How did you configured the static IP address on FreeBSD?

FYI, the `receiving packet: invalid argument` error shouldn't block the DHCP to be enabled.

**Comment by mkap20** [comment]
@EugeneOne1 Seems that invalid argument error resolved. I just updated to the latest release (v0.107.0-a.119+c14bde28) and no longer get the `Cannot check if IP is static` error. The "Check for DHCP servers" button still does not seem to work though :/

**Comment by TheRandMan** [comment]
On the latest beta release (v0.107.0-b.6) I was able to successfully enable DHCP using the web GUI. I had to click "Check for DHCP servers" twice (both times gave me errors) then the "Enable DHCP" worked. 

I then successfully received an IP address on a device and was able to set a static address as well.

**Comment by EugeneOne1** [comment]
@mkap20, we've filed the new [issue](https://github.com/AdguardTeam/AdGuardHome/issues/3417) about the error, that still persists.  As far as I can tell, current issue is fixed (DHCP server is now could be turned on), so I'll close it for now.  Please feel free to open new issues if you find any other bugs on FreeBSD.

**Comment by jult** [comment]
This is still not solved, that is to say, when I try to enable it on a debian 12 server, it fails with something about "cannot set static IP", don't remember the exact warning. Probably because the server uses several alias IPv4 addresses, so it does not know which one to pick? What I don't understand is why can I not manually set the IP for the DHCP ? That would solve all problems here..
