### ISSUE TITLE
Rewrite ist case-sensitiv 

### ISSUE THREAD

**Issue by DannySotzny** [AdguardTeam/AdGuardHome#3351]
At Filter -> DNS Rewrite it is possible to use case sensitiv hostnames. AdGuard accept "test.abc.org" And "Test.abc.org" at the Same Time. But only processes the lower case!

### Prerequisites
- [ X ] I am running the latest version
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed

### Issue Details
 
I create a Rewrite for Test.abc.org and test.abc.org. One to 1.1.1.1 and the second to 2.2.2.2
When both are created, the IP is output from the lower case one.
If only the entry with the capital letter exists, nothing will be found.

### Expected Behavior
The UI should transform any Host to lower-case. 

### Actual Behavior
it accept any spelling but responds only to the lower case variant

#### Both are created:
![image](https://user-images.githubusercontent.com/14806755/125436734-bfb16b18-dc15-4ee1-816f-4d8fec2fef24.png)
#### Only the false is created
![image](https://user-images.githubusercontent.com/14806755/125436749-5eea83cc-31ce-4529-a314-e46c9aa0d8b0.png)

**Comment by ainar-g** [comment]
This could be a dup of #3335, which is fixed on the `edge` channel.  Can you please look if the fix for that issue also fixes yours?

**Comment by DannySotzny** [comment]
> This could be a dup of #3335, which is fixed on the `edge` channel. Can you please look if the fix for that issue also fixes yours?

With the current EDGE version, which was uploaded to the Docker Hub an hour ago, the error persists.
I create a redirect for "Test.abc.de". AdGuard finds nothing. If I then create one for "test.abc.de", it gives a response (previously NXDOMAIN).

**Comment by ainar-g** [comment]
I see, thanks.  We'll look into it.

**Comment by ainar-g** [comment]
We have added another fix as of revision 1674475 on the `edge` channel.  Could you please check if the issue is now fixed?

**Comment by DannySotzny** [comment]
Ok, now it works correctly. When inserting, the domain is converted to lower case and the error no longer occurs. 👍
