### ISSUE TITLE
parental, safebrowsing and safesearch not working

### ISSUE THREAD

**Issue by derwotograf** [AdguardTeam/AdGuardHome#5230]
I'm having issues for parental, safebrowsing and safesearch:

from the log
```
/control/parental/enable: only content-type application/json is allowed
control/safebrowsing/enable: empty body with content-type "application/octet-stream" not allowed
/control/parental/enable: empty body with content-type "application/octet-stream" not allowed
/control/safesearch/enable: empty body with content-type "application/octet-stream" not allowed
```

message which appears in the frontend when trying to set functions to on:
`Error: control/safebrowsing/enable | empty body with content-type "application/octet-stream" not allowed | 415`

I'm running AdGuard as Add-on in Home Assistant.

Filtering is turned on and working. For testing I'm afraid to turn it of because it might not let me turn it back on again.

_Originally posted by @derwotograf in https://github.com/AdguardTeam/AdGuardHome/issues/5210#issuecomment-1336171401_

**Comment by Die-Sebis** [comment]
Hey, i have the same issue.

Trying to enable >

AdGuard Webservice fuer Internetsicherheit nutzen
AdGuard Webservice fuer Kindersicherung verwenden
Sichere Suche verwenden

dose not work.

Error: control/safesearch/enable epmty Body with content-tape ....

**Comment by ainar-g** [comment]
Sorry for the late response.  See #5116 and hassio-addons/addon-adguard-home#359.  Seems like one of the upcoming releases of the HomeAssistant addon should fix this.

**Comment by ZuluPilgrim** [comment]
Not sure if I am missing but the recent releases do not appear to have fixed this. I am now running 2022.12.8 and have the same issue.

**Comment by stamandr** [comment]
It is still not working after the recent Supervisor update and update to AdGuard Home version: 4.7.6.

Parental Control, Safe browsing and Safe search cannot be toggled off in the integration

Home Assistant 2022.12.8
Supervisor 2022.12.1
Frontend 20221213.1 - latest

AdGuard Home
Current version: 4.7.6
