### ISSUE TITLE
Adguard doesn't resolve any address - FreeBSD/ports/raspberry pi/etc

### ISSUE THREAD

**Issue by knaggsy2000** [AdguardTeam/AdGuardHome#6500]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD, ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

Current

### Action

In the past, I've used Adguard on a PI4B before without any issues (via Debian/Raspian).  Now, as adguard provides FreeBSD versions I've installed FreeBSD 14 onto the SD card - which is currently v14.

That installation went fine and whether I install AG via the ports or by the guide provided by AG, it does NOT seem to work as intented to my clients.   I have mutliple VLANS, which all was setup via rc.conf - that shouldn't make difference to my setup.

But no matter what, even after a reboot of the adguard device - NOTHING seems to be able to resolve DNS addresses.  I thought it was some issue with sysctl, but I don't think it is.  This is causing outages by the adguard device, but I can't work out why.

For a test on the PI itself, I installed unbound and configured it to forward queries (same as AG to the same forwarders) - and it worked completely fine.  So the issue is completely with Adguard - even looking at the webpage it claims the process was "processed" when it actually wasn't - WOW.

If you need more info, please don't hesitate to ask.

### Expected result

I expect DNS results to be passed onto the client

### Actual result

Nothing passed onto the client, so therefore the device just hung

**Comment by gspannu** [comment]
Can you test with version b49? Does the previous older version work? 

You can download this manually...  
`https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.49/AdGuardHome_freebsd_arm64.tar.gz
`

**Comment by ainar-g** [comment]
@knaggsy2000, hello.  Can you reach the AdGuard Home instance using `dig`?  If you enable the [verbose logging](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog), do you see any queries reaching it?

>  So the issue is completely with Adguard - even looking at the webpage it claims the process was "processed" when it actually wasn't

Can you elaborate on that?  If a query can be seen on the *Query log* page in AdGuard Home's UI then AdGuard Home processed it.  Did the client not receive a response or are you taking about some other “processed” status somewhere else?

**Comment by knaggsy2000** [comment]
> @knaggsy2000, hello. Can you reach the AdGuard Home instance using `dig`? If you enable the [verbose logging](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog), do you see any queries reaching it?
> 
> > So the issue is completely with Adguard - even looking at the webpage it claims the process was "processed" when it actually wasn't
> 
> Can you elaborate on that? If a query can be seen on the _Query log_ page in AdGuard Home's UI then AdGuard Home processed it. Did the client not receive a response or are you taking about some other “processed” status somewhere else?

No - using "drill", "dig", "nslookup", etc doesn't seem to work from the clients.  Even doing a "drill" from the device itself ("drill www.amazon.co.uk @127.0.0.1") doesn't resolve, it just returns after several seconds "Error: error sending query: Could not send or receive, because of network error".  I don't understand why, as the AD webpage said it was "processed" from the client and clicking on "test upsteams" on the web interface returns positive (same for if I "dig", "drill", etc the upstream server - it returns a valid result).  This is why I thought it might have been a NIC issue, but as stated setting up unbound with all the relevant "allow" rules for the VLANs, unbound works perfectly.

I think that "processed" means in the AD interface as in itself processed it internally but never actually forwarded it to the upstream servers.  There isn't any clarification.

I would really like to resolve this issue.  It updated to v0.107.42 yesterday and the issue it still present, even after a reboot.

**Comment by knaggsy2000** [comment]
> Can you test with version b49? Does the previous older version work?
> 
> You can download this manually... `https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.49/AdGuardHome_freebsd_arm64.tar.gz `

What's different with this version compared to the latest?

**Comment by vincejv** [comment]
@knaggsy2000 I have the same issue when i upgraded to `v0.107.42`, try to roll back to `v0.107.41`, it might be related to this issue https://github.com/AdguardTeam/AdGuardHome/issues/6506

**Comment by knaggsy2000** [comment]
@vincejv The issue was still present with v0.107.41 for me and continues with .42 too - just re-tested things.

**Comment by knaggsy2000** [comment]
@gspannu v0.108.0-b.49 still appears not to work for clients (";; connection timed out; no servers could be reached")
v0.108.0-b.51 is the same too.

**Comment by knaggsy2000** [comment]
@vincejv Noticed in that issue you gave me mentioned about editing the YAML file by setting the bind addresses to individual IPs (for every interface) rather than just "0.0.0.0".  Just tested this with v0.108.0-b.51 and it working - even "drill" on localhost is working ^^.

Going to revert back to the stable release (v0.107.42 as of this time) to see if that change works for that too...

**Comment by knaggsy2000** [comment]
@vincejv Yep, it's a "bind" issue in the YAML.  It completely works perfectly in v0.107.42 as long as you stop the service, edit the YAML to remove "0.0.0.0" and then include all the interface addresses (including "127.0.0.1").  Reboot tested too.  Many internet points for you, sir!

**Comment by knaggsy2000** [comment]
@ainar-g I see that you're a contributor to this repo, the issue has been found - it's that the "bind" address (in the YAML) if "0.0.0.0" doesn't actually seem to work for some reason.  As defining every interface IP makes everything work, even in the current stable version.

**Comment by ainar-g** [comment]
@knaggsy2000, we've fixed an issue with that in the most recent release.  Please check if it fixes the issue for you as well.

**Comment by knaggsy2000** [comment]
@ainar-g I've installed v0.107.43 on my backup PI (PI3 on FreeBSD 14) and used the same config as my main PI but in the "bind" section of the YAML only left "0.0.0.0".  Unfortunately, it still doesn't work as intended - exact same issues as originally mentioned.  Putting in each of the interface addresses including "127.0.0.1" resolves this.

My main interface has multiple VLANs defined too.

**Comment by ainar-g** [comment]
@knaggsy2000, it's really weird, because the fix was for all Unix(-ish) systems.  Have you been able to collect the verbose logs [as mentioned here](https://github.com/AdguardTeam/AdGuardHome/issues/6500#issuecomment-1847194647)?

**Comment by knaggsy2000** [comment]
> @knaggsy2000, it's really weird, because the fix was for all Unix(-ish) systems. Have you been able to collect the verbose logs [as mentioned here](https://github.com/AdguardTeam/AdGuardHome/issues/6500#issuecomment-1847194647)?

@ainar-g I've enabled verbose logs and looked for any errors reported.  Spotted this: -

`2023/12/18 23:12:57.447525 36428#45 [info] Creating a QUIC listener
2023/12/18 23:12:57.448857 failed to increase receive buffer size (wanted: 2048 kiB, got 41 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.`

So I followed that URL and then set buffer as recommended by that article with `sysctl -w kern.ipc.maxsockbuf=3014656` and restarted AG which no longer produces that message in the log.  But that didn't resolve the issue.

I can see that AG is setting up listeners for all the interfaces (including VLANs) - as `netstat -an` shows it too.  But issuing "nslookup" (from remote clients) now only seems to be replied on the main interface IP and NONE of the VLANs.

But now, even putting in the interface IPs in the YAML does NOT work anymore on my PI3 - whereas on the PI4 it is still working.

Something weird is certainly going on, can't quite work it out at the moment.  Doing more testing...

**Comment by knaggsy2000** [comment]
@ainar-g Even just defining the main IP, localhost, and one VLAN even seems to not to work (on that VLAN, at least - on the main IP it's resolving).  I've disabled the firewall (pf) in-case that was the issue, but it wasn't.

**Comment by ainar-g** [comment]
@knaggsy2000, are you entirely sure that this is v0.107.43?  Also, can you try using `dig` instead of `nslookup`?  It reports more information, including warnings about a reply coming from an unexpected address, which was the issue fixed in v0.107.43.  Also, if you could launch AGH with `"0.0.0.0"`/`"::"` bind address(es), make a few queries, and send the verbose logs to <devteam@adguard.com>, we would inspect them to see if there's something wrong with them.

**Comment by knaggsy2000** [comment]
@ainar-g Yes, 100% as I've previously mentioned I made a clean install of v0.107.43 on the PI3 and that's where I'm now testing things - confirmed with the web interface and SSH: `2023/12/19 23:48:00 [info] AdGuard Home, version v0.107.43.`  As for using "dig", I was testing from an OpenWRT device which doesn't have that installed and memory/disk space is **very** restricted with those boxes.  I run a multiple-OS network.

How do you want me to launch AG with those arguments?

`Usage:

/opt/AdGuardHome/AdGuardHome [options]

Options:
  -c, --config VALUE                 Path to the config file.
  -w, --work-dir VALUE               Path to the working directory.
  -h, --host VALUE                   Deprecated. Host address to bind HTTP server on. Use --web-addr. The short -h will work as --help in the future.
  -p, --port VALUE                   Deprecated. Port to serve HTTP pages on. Use --web-addr.
  --web-addr VALUE                   Address to serve the web UI on, in the host:port format.
  -s, --service VALUE                Service control action: status, install (as a service), uninstall (as a service), start, stop, restart, reload (configuration).
  -l, --logfile VALUE                Path to log file.  If empty, write to stdout; if "syslog", write to system log.
  --pidfile VALUE                    Path to a file where PID is stored.
  --check-config                     Check configuration and exit.
  --no-check-update                  Don't check for updates.
  --update                           Update the current binary and restart the service in case it's installed.
  --no-mem-optimization              Deprecated.  Disable memory optimization.
  --no-etc-hosts                     Deprecated: use clients.runtime_sources.hosts instead.  Do not use the OS-provided hosts.
  --local-frontend                   Use local frontend directories.
  -v, --verbose                      Enable verbose output.
  --glinet                           Run in GL-Inet compatibility mode.
  --version                          Show the version and exit.  Show more detailed version description with -v.
  --help                             Print this help.`

**Comment by knaggsy2000** [comment]
Not sure why that didn't parse with the "code" option :/

**Comment by ainar-g** [comment]
You don't have to install `dig` on that exact device, assuming that the device itself is available over a network.

> How do you want me to launch AG with those arguments?

If you mean the bind address, they're set in the configuration file, in the `dns.bind_hosts` array.  See [our documentation for the configuration file](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration).

**Comment by knaggsy2000** [comment]
@ainar-g Putting "0.0.0.0" in the YAML is fine (in regards to the service starting up), but also including "::" for the bind address causes AG not to start with `[error] parsing configuration file: dns.bind_hosts at index 1 is not a valid ip address` - that's because IPv6 is NOT enabled on the OS so therefore they aren't IPv6 addresses to bind to (but can be easily enabled via rc.conf).

But even so with just "0.0.0.0" in the YAML, it still replies on the main interface IP - just not on any other interface (which are all VLANs).  Don't see a reason to e-mail the log file as NONE of the queries on the VLANs are even mentioned in it, just the requests from the main interface IP: `2023/12/21 22:33:27.152765 18497#45 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: NOERROR, id: 15957
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;www.google.co.uk.	IN	 AAAA

;; AUTHORITY SECTION:
www.google.co.uk.	10	IN	SOA	fake-for-negative-caching.adguard.com. hostmaster.www.google.co.uk. 100500 1800 60 604800 86400`

Comment: What's with the "fake-for-negative-caching.adguard.com" in that?


With `netstat -an` I can see the interfaces are listening on the expected DNS ports (output filtered to show only relevant): -

`Proto Recv-Q Send-Q Local Address          Foreign Address        (state)    
tcp46      0      0 *.853                  *.*                    LISTEN 
tcp46      0      0 *.53                   *.*                    LISTEN
udp46      0      0 *.853                  *.*                    
udp46      0      0 *.53                   *.*`

Any more ideas?

**Comment by knaggsy2000** [comment]
@ainar-g I spotted a mistake (*facepalm*) with the managed switch that handled traffic to the backup PI - which I've now corrected.  Currently testing it with only just "0.0.0.0" in the YAML with version v0.107.43.  Watch this space...

**Comment by knaggsy2000** [comment]
@ainar-g Update: Nope, just having "0.0.0.0" in the YAML config still doesn't work.  Once I defined all the interface IPs it works as intended.

**Comment by mattxtaz** [comment]
Just a note to say I'm still seeing the same thing on FreeBSD which has both an IPv4 and IPv6 IP address on the interface. This worked fine on 0.107.41 and earlier (I think?). 0.107.42 broke *all* resolution. And 0.107.43 broke resolution only on IPv4. IPv6 works fine. I may be slightly wrong on these version numbers, it possibly broke one version earlier, but I'm not sure now.

As mentioned above, editing the yaml and changing the bind from 0.0.0.0 to list both the IPv4 and IPv6 IPs fixes it.

With 0.0.0.0 netstat -an shows (and resolution only works on v6):

tcp46      0      0 *.53                   *.*                    LISTEN
udp46      0      0 *.53                   *.*

With both interfaces configured netstat -an shows (and resolution works fine on both v4 and v6):

tcp6       0      0 2a02:390:878a::1.53    *.*                    LISTEN        
tcp4       0      0 10.0.0.10.53           *.*                    LISTEN     
udp6       0      0 2a02:390:878a::1.53    *.*                                                                                                                   
udp4       0      0 10.0.0.10.53           *.*                     

Interestingly a tcpdump of the traffic to v4 when it's broken shows a proper request/response to/from the correct IPs and source ports, so I'm wondering if it's something in the actual DNS payload it doesn't like.

**Comment by knaggsy2000** [comment]
@mattxtaz Interesting...  I've (currently) only got IPv4 addresses stated by static addresses defined in rc.conf, but I do use IPv6 so in-future they will be added.  v0.107.41 for me still didn't work when I tested that version (my first post mentions all the versions I've tested so far).  In regards to the "client computer", which OS was that running for your tests?  And how about the architecture?  I've tried FreeBSD and Linux which both don't give a response - ie. timeouts.

**Comment by knaggsy2000** [comment]
Issue still happens with v0.107.44 - thought it was worth a check.

Any update on this issue?

**Comment by knaggsy2000** [comment]
Any update on this issue?

**Comment by knaggsy2000** [comment]
@ainar-g Any update on this?

**Comment by knaggsy2000** [comment]
v0.107.45 - still doesn't work
 v0.108.0-a.858+36f9feca - still doesn't work

**Comment by knaggsy2000** [comment]
@ainar-g Issue STILL not resolved.

**Comment by knaggsy2000** [comment]
Just tried v0.108.0-a.860+64090115 and still the same.

**Comment by knaggsy2000** [comment]
@Mizzick My backup PI updated again today (as I logged in to the web interface), would you me to like to re-test with this version?

**Comment by Mizzick** [comment]
@knaggsy2000 hello!

I've tested it on my side.

So I put `/etc/rc.conf`:
```
cloned_interfaces="vlan0"
ifconfig_vlan0="inet 10.0.0.1 netmask 255.255.255.0 vlan 2 vlandev em0"
```

Then I restarted the machine and it works as expected.

I'm not sure, but I think the issue is more about vlan configuration here. Can you please check your configuration?

**Comment by openglx** [comment]
Hi folks,
Jumping in to add a few data points.
I'm also on FreeBSD (amd64), and tested version v0.108.0-b.54 as was having same problems as the original poster.

My setup is:
- various clients (MacOS, Android, other boxes), all on same 192.168.1.0/24 subnet
- AdGuard runs on a Jail on a FreeBSD 14 host, this is a vnet-enabled jail (epair53a/b) linked to bridge0, also linked to the host's Ethernet device, no VLAN
- no DHCP on AdGuard, using router's DHCP
- static IP on host, static IP on AdGuard jail
- IPv6 on host but not on the Jail
- very open `ipfw`
- host has `net.inet.ip.forwarding=1`

I'm able to verify that this networking setup works by stopping AdGuard and running pdns-recursor on the very same jail.
With pdns-recursor, all clients work.

When I stop pdns-recursor and start AdGuardHome, one of the clients will get DNS answers but not the others.
Looking at the tcpdump from the host point of view (can't tcpdump on the jail, "there are no BPF devices"), what I found very curious was that the MAC address used on the packets is always the same.

e.g. reply for one client 
```
23:08:35.634830 IP (tos 0x0, ttl 64, id 24252, offset 0, flags [none], proto UDP (17), length 164)
    192.168.1.53.53 > 192.168.1.108.57664: [udp sum ok] 63992 q: A? thor.sslauth.sonos.com. 3/0/0 thor.sslauth.sonos.com. CNAME thor.sslauth.sonos.com.edgekey.net., thor.sslauth.sonos.com.edgekey.net. CNAME e177.a.akamaiedge.net., e177.a.akamaiedge.net. A 2.22.65.151 (136)
        0x0000:  f0a7 3143 ab34 027f 193b 9d0b 0800 4500  ..1C.4...;....E.
```

compare with the reply to another client:
```
23:08:39.722321 IP (tos 0x0, ttl 64, id 6518, offset 0, flags [none], proto UDP (17), length 103)
    192.168.1.53.53 > 192.168.1.104.56629: [udp sum ok] 13094 q: A? instantmessaging-pa-jms-eu.googleapis.com. 1/0/0 instantmessaging-pa-jms-eu.googleapis.com. A 216.239.36.158 (75)
        0x0000:  f0a7 3143 ab34 027f 193b 9d0b 0800 4500  ..1C.4...;....E.
```

It's a bit suttle but `192.168.1.108` and `192.168.1.104` are two different hosts, and they certainly don't have the same MAC address `f0:a7:31:43:ab:34`.

It's a bit more concerning that that's none of their MAC addresses at all, but rather of a completely different client:

```
? (192.168.1.104) at 6a:d7:cb:87:4c:5c on epair53b expires in 1063 seconds [ethernet]
? (192.168.1.108) at 78:28:ca:c5:cf:02 on epair53b expires in 1162 seconds [ethernet]
? (192.168.1.166) at f0:a7:31:43:ab:34 on epair53b expires in 1162 seconds [ethernet]
```

If I go on that client 192.168.1.166 I'll see the queries of all other clients trying to reach me.

I'm new to AdGuard so have no idea whether you folks are bringing your own DNS server to the mix but, somehow, it's writing UDP packets for the wrong destination.

To really test this you need at least two, ideally many clients.

Thanks for your time, let me know if you want me to test anything different or provide more of my config.

**Comment by knaggsy2000** [comment]
@Mizzick All of my VLANs have been cloned and setup as per FreeBSD documentation (same as yours but MULTIPLE), yet AdGuard doesn't seem to find them while the "bind address" is "0.0.0.0" - I STILL have to define each IP in the AdGuard YAML.

@openglx Glad to see another FreeBSD user finding this issue, even in a slightly different scenario - ie.  a jail.  But not even running VLANs.

**Comment by openglx** [comment]
> @openglx Glad to see another FreeBSD user finding this issue, even in a slightly different scenario - ie. a jail. But not even running VLANs.

I was thinking we didn't have the same bug, but it might be.

I changed my `dns.bind_hosts` from `0.0.0.0` to `127.0.0.1, 192.168.1.53` on the yaml and restarted, and now I'm seeing the UDP packets working correctly.

One of my easiest tests is to disconnect an Android from WiFi, connect again, and see whether it gets the connection or not. Before, they would get a "No Internet Connection" error.
After changing to explicit `dns.bind_hosts`, it connects automatically.
I'm keep an eye on it and see whether it stops working after a few hours/days.

@knaggsy2000 are you able to try and `tcpdump` the interface binding your VLANs? I don't recall how many bytes (14 for the VLAN header?) you will have to skip but you are looking for the top of the packet, the destination MAC address for various different clients?
Depending on your network layout, can't you use routing instead of bridging all those VLANs into the AdGuard computer?

**Comment by gspannu** [comment]
I think the issue is that FreeBSD (DHCP server) does not hand out a primary DNS resolver for a 3rd party resolver. So, it works fine with dnsmasq/Unbound but not for any 3rd party DNS resolver.

**This issue was noticed by OPNsense (FreeBSD variant) users who were using the community repo AGH plugin.** 

The solution (in OPNsense) was to either
- have the DNS addresses manually specified in the DHCP server
- list all DNS resolver addresses in AGH config file (instead of 0.0.0.0)

Eventually, the plugin author fixed this with a solution within the AGH plugin for OPNsense... and this was to inform OPNsense that primary DNS resolver is running on port 53.
$services[] = array('dns_ports' => ['53'])

_Maybe reading the below can give some ideas... to build a fix for FreeBSD._

https://github.com/mimugmail/opn-repo/issues/153
https://github.com/opnsense/core/issues/6513#issuecomment-1516642071

Another way to test this theory is to maybe use another 3rd party DNS resolver (e.g. Blocky instead of AGH) and to test if FreeBSD shows the same behaviour... I suspect that FreeBSD DHCP will not hand out a DNS resolver address with both Blocky and AGH.

**Comment by knaggsy2000** [comment]
@openglx I've mentioned my previous testing methods earlier.

@gspannu My current DHCP server is actually OPNsense too.  But AGH is NOT installed on it, only my PIs as dedicated servers.  But the issue seems to deepens...

**Comment by gspannu** [comment]
> @gspannu My current DHCP server is actually OPNsense too. But AGH is NOT installed on it, only my PIs as dedicated servers. But the issue seems to deepens...

1) Are you running Unbound or dnsmasq on your OPNsense (DHCP server)?
2) What is the output of  `cat /etc/resolv.conf` on your OPNsense?

**Comment by knaggsy2000** [comment]
> > @gspannu My current DHCP server is actually OPNsense too. But AGH is NOT installed on it, only my PIs as dedicated servers. But the issue seems to deepens...
> 
>     1. Are you running Unbound or dnsmasq on your OPNsense (DHCP server)?
> 
>     2. What is the output of  `cat /etc/resolv.conf` on your OPNsense?

1. Unbound
2. Why does that matter?  As it's overridden by DHCP anyway - to point to the PIs.

**Comment by Mizzick** [comment]
@knaggsy2000 any updates here? Have you tried the latest release?

**Comment by knaggsy2000** [comment]
@Mizzick Are we talking stable or unstable?

**Comment by Mizzick** [comment]
@knaggsy2000 I mean the edge channel, as it contains latests changes.

**Comment by dallenwilson** [comment]
@knaggsy2000 Try adding `options single-request-reopen timeout:2` to your `/etc/resolv.conf` on one of the clients displaying the problem, and see if it helps.

I had similar (not identical) problems to yours: dns resolution failures across multiple (*nix) clients (Windows and Android always worked fine), yet AdGuard's query log showed the requests were received, processed, and responded to, in every case. Worse, completely disabling ipv6 on the clients fixed it, but even with ipv6 enabled, most 'high level' applications (eg, a web browser) on the *nix boxes also worked just fine, it was the lower-level, console commands that were failing. But not all of them: ping or wget would fail, but curl would work, for example. Every program that was failing, used glibc for DNS to resolve hostnames, and that eventually led me to the above fix.

From what I saw, it boiled down to the glibc-users sending requests for A and AAAA records at the same time, from the same source port/tcp connection, but AdGuardHome would only reply to the AAAA, leaving the A to time-out and trigger a name resolution failure on the client's end, since I'm not set up to actually use IPv6 outside my local network. The `single-request-reopen` option forced glibc to send one request per connection, instead, so an A record always came back.

I should have opened an issue about it then, and almost did today rather than responding here, but it's been over six months since I ran in to this and solved it with the above work-around, and I just can't bring myself to re-create it and collect all the detailed, verbose output and wireshark logs again. Sorry, AdGuard-team.

Edit - it was (still is) AdGuardHome 0.107.57 on an OpenWRT device. Perhaps it's been addressed since then, but OpenWRT hasn't updated it's ADH package in a while, and I don't want to break anything by manually updating it just to find out.
