### ISSUE TITLE
Youtube Comments for this video have been hidden by Restricted Mode.

### ISSUE THREAD

**Issue by fathinfadillah** [AdguardTeam/AdGuardHome#7084]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Comments for this video have been hidden by Restricted Mode.

### Proposed solution

maybe it can be opened for limited mode on YouTube

**Comment by Dynamic5912** [comment]
This is part of enabling Safe Search for YouTube

**Comment by Inc44** [comment]
Actually, the problem persists even when force safe search is completely disabled

**Comment by Dynamic5912** [comment]
> Actually, the problem persists even when force safe search is completely disabled

What problems?

**Comment by Inc44** [comment]
> > Actually, the problem persists even when force safe search is completely disabled
> 
> What problems?

Sorry for the disturbance. The issue has been fixed. I thought it was strange that comments were hidden despite Safe Search being off, but it was actually a DNS provider problem

**Comment by johnnyv5** [comment]
I am experiencing this same issue.  I have Safe Search turned off but still get Restricted mode for comments.  Mind sharing your fix?

**Comment by Dynamic5912** [comment]
> I am experiencing this same issue.  I have Safe Search turned off but still get Restricted mode for comments.  Mind sharing your fix?

What dns servers are you using?

**Comment by johnnyv5** [comment]
> > I am experiencing this same issue.  I have Safe Search turned off but still get Restricted mode for comments.  Mind sharing your fix?
> 
> What dns servers are you using?

Sorry should have responded that I fixed it by changing to Google's DNS servers.  If there are others I should use instead, please let me know.
