### ISSUE TITLE
Dashboard query statistics not working after upgrade to v0.107.55

### ISSUE THREAD

**Issue by ewosborne** [AdguardTeam/AdGuardHome#7501]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On one machine

### AdGuard Home version

  v0.107.55

### Action

I'm running AGH as a plugin on OPNsense.  Yesterday AGH prompted me to update to so I did. I'm now getting an error on the AGH web page:
    
    Error: control/clients/find?ip0=192.168.1.111&ip1=192.168.1.189&ip2=192.168.1.137&ip3=192.168.1.182&ip4=192.168.1.201&ip5=192.168.1.202&ip6=192.168.1.84&ip7=192.168.1.123&ip8=192.168.1.72&ip9=192.168.1.186&ip10=192.168.1.196&ip11=192.168.1.188&ip12=10.10.10.2&ip13=192.168.1.96&ip14=192.168.1.10&ip15=192.168.1.203&ip16=192.168.1.94&ip17=192.168.1.124&ip18=192.168.1.76&ip19=192.168.1.9&ip20=192.168.1.80&ip21=192.168.1.125&ip22=192.168.1.102&ip23=192.168.1.97&ip24=192.168.1.131&ip25=192.168.1.101&ip26=192.168.1.95&ip27=192.168.1.99&ip28=192.168.1.86&ip29=192.168.1.93&ip30=192.168.1.117&ip31=192.168.1.119&ip32=192.168.1.104&ip33=192.168.1.115&ip34=192.168.1.122&ip35=192.168.1.113&ip36=192.168.1.130&ip37=192.168.1.183&ip38=192.168.1.81&ip39=192.168.1.87&ip40=192.168.1.73&ip41=192.168.1.75&ip42=192.168.1.83&ip43=192.168.1.79&ip44=192.168.1.71&ip45=192.168.1.127&ip46=192.168.1.82 | Network Error

The rest of the UI works fine - I can toggle services on and off, for example.  Logging out and back in again didn't help and restarting the service from the OPNsense control panel didn't either.

### Expected result

I expected to see query and filter statistics.  They're all coming back as zero.

### Actual result

<img width="1097" alt="Screenshot 2024-12-12 at 9 22 17 AM" src="https://github.com/user-attachments/assets/fae47c93-7629-4a68-b4b6-a185be1e6118" />

### Additional information and/or screenshots

Not sure what's going on...what can I gather to help debug?

**Comment by papampi** [comment]
Same problem with docker latest version I posted https://github.com/AdguardTeam/AdGuardHome/issues/5955#issuecomment-2538187520

**Comment by condraj2** [comment]
Exact same issue here; glad it's not just me! Was working just fine pre-update.

**Comment by ainar-g** [comment]
Please enable [verbose logging](https://adguard-dns.io/kb/adguard-home/faq/#verboselog) and see what errors are there, if any.  If you don't see the query in the logs at all, it is likely that it's something along the lines of #4358 and #6269.  That is, the reverse proxy refusing the to proxy the query, because the querystring is too long.

**Comment by BallBill** [comment]
I turn off uBlock Origin Lite, adguard home back to normal

**Comment by zagorodnovv** [comment]
> I turn off uBlock Origin Lite, adguard home back to normal
> 
> [uBlockOrigin/uBOL-home#256](https://github.com/uBlockOrigin/uBOL-home/issues/256)

I confirm that it worked!

**Comment by condraj2** [comment]
Disabling uBlock did it for me too!

**Comment by papampi** [comment]
Fixed with latest uBlock Origin Lite update

**Comment by diegoweb** [comment]
Still happens with Brave Shield (which is a fork from uBlock Origin). Their filters hasn't been update yet.
