### ISSUE TITLE
Custom encrypted DNS upstream servers configured for a client are 4-5 times slower

### ISSUE THREAD

**Issue by hagezi** [AdguardTeam/AdGuardHome#7769]
### Prerequisites

- [x] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [x] I have searched other issues and found no duplicates

- [x] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [x] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.108.0-b.66

### Action

If custom encrypted DNS servers are configured for a client, the resolution times for this client are 4-5 times higher than the same standard configured encrypted DNS servers. If legacy DNS via IP is used instead, the problem does not occur.

Settings > Client Settings > Add/Edit Client
Tab Upstream DNS servers > Configure encrypted DoT or DoH Servers for the Client > Save > Test

### Expected result

Same resolution times as with the standard configured encrypted upstream DNS servers.

### Actual result

Resolution times are 4-5 times higher than the same standard configured encrypted DNS servers.

**Comment by bohtho** [comment]
I have the same observation and problem, and I think it may be related to [this issue](https://github.com/AdguardTeam/AdGuardHome/issues/7739), because that's the error I also get in my log. But it seems to only affect persistent clients considering response times in the query log.

**Comment by fbernier** [comment]
I may have a fix for this but it's still unconfirmed. Please give it a try if you'd like: https://github.com/AdguardTeam/AdGuardHome/pull/7789

**Comment by tjharman** [comment]
Thanks @fbernier I'll make the team aware of this.

**Comment by bohtho** [comment]
> I may have a fix for this but it's still unconfirmed. Please give it a try if you'd like: https://github.com/AdguardTeam/AdGuardHome/pull/7789

I run adguard home with a certain complicated installer on my router so I think I have to wait for it to get merged into edge unfortunately...

**Comment by fbernier** [comment]
> > I may have a fix for this but it's still unconfirmed. Please give it a try if you'd like: [#7789](https://github.com/AdguardTeam/AdGuardHome/pull/7789)
> 
> I run adguard home with a certain complicated installer on my router so I think I have to wait for it to get merged into edge unfortunately...

I thought it would be a hassle too but turns out that cloning the repo on a linux desktop, running a single command to cross-compile to a single arm64 binary (`make GOOS='linux' GOARCH='arm64'), `scp`-ing it to my router, `docker cp` it to my docker container and restarting the container was pretty quick.

**Comment by bohtho** [comment]
> > > I may have a fix for this but it's still unconfirmed. Please give it a try if you'd like: [#7789](https://github.com/AdguardTeam/AdGuardHome/pull/7789)
> > 
> > I run adguard home with a certain complicated installer on my router so I think I have to wait for it to get merged into edge unfortunately...
> 
> I thought it would be a hassle too but turns out that cloning the repo on a linux desktop, running a single command to cross-compile to a single arm64 binary (`make GOOS='linux' GOARCH='arm64'), `scp` -ing it to my router, `docker cp` it to my docker container and restarting the container was pretty quick.
> 
> Here's an arm64 binary in case anyone's interested: https://drive.google.com/file/d/1NeGDB0tyX6A523Cp0GHC-M-Mqjturwcj/view

Thanks, but my router uses armv7 architecture for most binaries, so it would really be much quicker and easier if maintainers would just merge this one-liner PR, which also actually fixes something that made the persistent client part of agh quite unusable since forever.

**Comment by hagezi** [comment]
ping @ainar-g

**Comment by tjharman** [comment]
I've made the AGH team aware of this already - no need to @ people.

**Comment by ainar-g** [comment]
Thanks for reporting!  We've found that bug as well, and we're aiming to fix it in the next beta.  Assigning to @schzhn, who is currently working on the fix.

**Comment by schzhn** [comment]
The fix is already in the [edge release](https://github.com/AdguardTeam/AdGuardHome/blob/master/README.md#test-unstable-versions). You can download the binary for your platform from this [page](https://static.adtidy.org/adguardhome/edge/version.json).

**Comment by bohtho** [comment]
Did the fix for this in edge somehow negate the fix for the custom caches that was just merged days ago...?

**Comment by ainar-g** [comment]
@bohtho, I'm not sure what you mean.  Do you see any issues on the edge channel currently?

**Comment by hagezi** [comment]
@ainar-g The custom client cache function does not seem to be used/working.

**Comment by hagezi** [comment]
Docker edger version v0.108.0-a.1089+2c46bc92 fixes the problem for me and the custom client cache also seems to work.

**Comment by ainar-g** [comment]
@bohtho, I cannot reproduce that on the current edge release.  There is a separate issue where disabling the global cache also disables custom caches, and we're working on that at the moment, and it should be fixed by the next beta release.

**Comment by bohtho** [comment]
Leaving the global and custom caches at the same level (and turned on) the custom persistent clients definitely misses a lot in the cache even after several days. But suddenly some things are taken from cache too so I can't figure it out or pin it down.

**Comment by bohtho** [comment]
Anyone else still seeing that the custom client caches are not working (perhaps after the custom client upstream timeout fix) ?

**Comment by schzhn** [comment]
@bohtho, ensure that the custom client upstream DNS server list is not empty.
