### ISSUE TITLE
AdGuard Home Blocking Traffic Intermittently

### ISSUE THREAD

**Issue by LogicAnalysis** [AdguardTeam/AdGuardHome#8162]
### Prerequisites

- [x] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [x] I have searched other issues and found no duplicates

- [x] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [x] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.71

### Action

I've been using AdGuard Home for just over a year, and it has been working flawlessly. Over the past week, I have noticed that it intermittently blocks requests from websites that are NOT in the blocklist/filters. These requests are from many different locations, so I can't narrow it down to a single source. I don't see that it's blocking the specific request in the logs

### Expected result

Not to block things NOT in the filters/block lists

### Actual result

Things that are not in the filters/block lists are blocked

**Comment by Dynamic5912** [comment]
What makes you believe it's AGH blocking it?

Are you using cache/optimistic cache?

**Comment by LogicAnalysis** [comment]
> What makes you believe it's AGH blocking it?
> 
> Are you using cache/optimistic cache?

The issue is resolved immediately upon removing AGH from my DNS settings. Not sure about cache/optimistic cache; I'm not sure about the cache/optimistic cache settings. Whatever the default settings are, I'm using them.

**Comment by jphilebiz** [comment]
Having the same issue as OP for about a week now at two different locations. Both sites run Unifi firewalls and AGH runs in a Proxmox Ubuntu VM for self only.

**Comment by Mave922** [comment]
I have been experiencing the same issue for about a week. Even after updating to the latest version the intermittent slowness/blocking still persists.

**Comment by andremieth** [comment]
I have noticed a similar issue for about two weeks now.
Clients (Windows PCs and several iPhones) seem to experience that multiple apps stop working for a few minutes with a “DNS name not found” error, but no blocks are logged in AGH.

Edit: Just looked in the network trace, example with app.wunschgutschein.de is getting a 'Server failure' without any additional log in AGH 

<img width="1636" height="591" alt="Image" src="https://github.com/user-attachments/assets/7a3cb474-eb58-41a0-97f2-f1e10cd5b350" />

Edit2: Switched from DoH to plain IPv4 (same provider, quad9) - so far, no issues.

**Comment by nlfth** [comment]
Same issue, Version: v0.107.71 running as an add-on on Home Assistant.
Legitimate sites, failures happen on both A and HTTPS records.

Workaround: using quad9 directly on the client no issues...

<img width="2056" height="1190" alt="Image" src="https://github.com/user-attachments/assets/ba25e8c9-2d4d-407f-8b58-cbb4297d4141" />

**Comment by ptweezy** [comment]
I am experiencing the exact same on v0.107.71

**Comment by mihajlov123** [comment]
Also using version 0.107.71 and experiencing the same issue as described.

**Comment by alinasrullayev** [comment]
I also have same issue. 

I'm running
Adguard Home: v0.107.71
OS: Android 15 (LineageOS 22.2)
Environment: Termux v0.118.3
CPU: ARM64

**Comment by jphilebiz** [comment]
Here is the info on my VM in case this helps the dev team pinpoint the issue, VM under Proxmox:

root@AdGuard
------------
OS: Ubuntu 25.04 x86_64
Kernel: Linux 6.8.12-15-pve
Uptime: 86 days, 18 hours, 17 mins
Packages: 361 (dpkg)
Shell: bash 5.2.37
Terminal: /dev/tty1
Terminal Font: VGA default kernel font
CPU: Intel(R) Core(TM) i5-6260U (2) @ 2.90 GHz
GPU: Intel Iris Graphics 540 @ 0.95 GHz [Integrated]
Memory: 300.89 MiB / 2.00 GiB (15%)
Swap: 23.22 MiB / 2.00 GiB (1%)
Disk (/): 3.73 GiB / 29.36 GiB (13%) - ext4

**Comment by Lling** [comment]
have the same issue

**Comment by dwagix** [comment]
It's affecting me as well

**Comment by aldo1066** [comment]
i also got that problem

**Comment by Dynamic5912** [comment]
More information from those with this issue would help the AGH team in diagnosing.

Device types, DNS servers etc....

**Comment by rossc123** [comment]
I was also having this issue. Yesterday I went into the DNS settings on AdGuard Home and changed my upstream DNS server to `https://dns.adguard-dns.com/dns-query` and I don't seem to be having issues anymore. Would be curious to know if this works for anyone else

**Comment by Lling** [comment]
Thanks for the info. I will test it.

**Comment by Dynamic5912** [comment]
> I was also having this issue. Yesterday I went into the DNS settings on AdGuard Home and changed my upstream DNS server to `https://dns.adguard-dns.com/dns-query` and I don't seem to be having issues anymore. Would be curious to know if this works for anyone else

What DNS server did you have set previously?

**Comment by rossc123** [comment]
> > I was also having this issue. Yesterday I went into the DNS settings on AdGuard Home and changed my upstream DNS server to `https://dns.adguard-dns.com/dns-query` and I don't seem to be having issues anymore. Would be curious to know if this works for anyone else
> 
> What DNS server did you have set previously?

I was using `https://dns10.quad9.net/dns-query` previously

**Comment by Lling** [comment]
> > > I was also having this issue. Yesterday I went into the DNS settings on AdGuard Home and changed my upstream DNS server to `https://dns.adguard-dns.com/dns-query` and I don't seem to be having issues anymore. Would be curious to know if this works for anyone else
> > 
> > 
> > What DNS server did you have set previously?
> 
> I was using `https://dns10.quad9.net/dns-query` previously

same

**Comment by Tsaihyun** [comment]
have the same issue

**Comment by sofvaskina** [comment]
Hello! It's not working for me. It seems there was an issue with the Quad9 DNS server at that time. To reduce the number of failures, I suggest you:
- Set `fallback_dns` (e.g. - `1.1.1.1`, `8.8.8.8`) so that a failed primary upstream doesn't prevent all resolution.

- Or set `upstream_mode: parallel` so that a failing upstream server doesn't block sequential resolution.
